### ISSUE TITLE
CoreML

### ISSUE THREAD

**Issue by albertoxamin** [stratospark/food-101-keras#4]
is it possible to convert this keras model to a CoreML model?

**Comment by stratospark** [comment]
@albertoxamin This project is using an older version of Keras and Tensorflow, so I'm not sure if it would be compatible with their conversion tool. It would be worth exploring though!

**Comment by albertoxamin** [comment]
Which version of keras is this?
because the coremltools coverter works with keras1.2.2

**Comment by stratospark** [comment]
I trained this using Keras 1.1.2 and Tensorflow 0.11.0

You may still be able to use the weights though.

**Comment by ph1ps** [comment]
I‘m on it right now, even though I was able to load the weights it gave me wrong results. Therefore I will need to retrain the whole thing. Wish me luck.

**Comment by albertoxamin** [comment]
@ph1ps any luck?

**Comment by ph1ps** [comment]
@albertoxamin Hmm not really. I tried to debug the preprocessing but I just found out that this is not the problem. I really have to retrain the whole model I guess...

**Comment by ph1ps** [comment]
@albertoxamin I finally did it. Will be uploading it soon!

Update: https://github.com/ph1ps/Food101-CoreML
@stratospark This issue can be closed.
